<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'RobinFasano\\Onepage\\' => array($typo3InstallDir . 'typo3conf/ext/onepage/Classes'),
);
